version: "2.2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  sql-client:
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    security_opt:
      - seccomp:unconfined
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager

  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "6123"
    command: jobmanager
    ports:
      - "8081:8081"
    security_opt:
      - seccomp:unconfined
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    security_opt:
      - seccomp:unconfined
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  python-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    ports:
      - "5000:5000"
    environment:
      AZURE_OPENAI_ENDPOINT: "https://keshav-openai-test.openai.azure.com"
      AZURE_OPENAI_KEY: "your-key"
      AZURE_OPENAI_DEPLOYMENT: "test_gpt35"

  fe-app:
    build:
      context: ./app-fe
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
